# Generated by Django 4.0.1 on 2022-11-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanage', '0002_rename_subjects_name_subjects_subject_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=255),
        ),
    ]
