# Generated by Django 4.0.1 on 2022-11-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanage', '0003_alter_courses_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
