# Generated by Django 4.0.1 on 2022-12-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanage', '0004_attendancereport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='staff_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
