# Generated by Django 4.0.1 on 2022-12-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanage', '0005_staffs_staff_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='staff_name',
        ),
    ]
