# Generated by Django 4.0.1 on 2022-12-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanage', '0006_remove_staffs_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='staff_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
